# Generated by Django 3.2.7 on 2021-10-18 23:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('logo', models.ImageField(upload_to='logos_ferias')),
                ('distrito', models.CharField(max_length=60)),
                ('canton', models.CharField(max_length=60)),
                ('provincia', models.CharField(max_length=60)),
                ('direccionExacta', models.CharField(max_length=260)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('horario', models.CharField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('nombre', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('imagenRepresentativa', models.ImageField(upload_to='productos')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('sitioWeb', models.URLField(max_length=100)),
                ('perfilInsta', models.URLField(max_length=100)),
                ('perfilFace', models.URLField(max_length=100)),
                ('logo', models.ImageField(upload_to='logos_vendedores')),
            ],
        ),
        migrations.CreateModel(
            name='TelefonosVendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(regex='^\\+?506?\\d{9,15}$')])),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferias.vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='TelefonosFeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(regex='^\\+?506?\\d{9,15}$')])),
                ('feria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferias.feria')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoVendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.CharField(max_length=5)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferias.producto')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferias.vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoFeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferias.feria')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferias.producto')),
            ],
        ),
    ]
