# Generated by Django 3.2.7 on 2021-10-19 00:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferias', '0002_feria_vendedores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('telefono', models.CharField(max_length=15, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='^\\+?506?\\d{9,15}$')])),
            ],
        ),
        migrations.RemoveField(
            model_name='productovendedor',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='productovendedor',
            name='vendedor',
        ),
        migrations.RemoveField(
            model_name='telefonosferia',
            name='feria',
        ),
        migrations.RemoveField(
            model_name='telefonosvendedor',
            name='vendedor',
        ),
        migrations.AddField(
            model_name='vendedor',
            name='productos',
            field=models.ManyToManyField(to='ferias.Producto'),
        ),
        migrations.DeleteModel(
            name='ProductoFeria',
        ),
        migrations.DeleteModel(
            name='ProductoVendedor',
        ),
        migrations.DeleteModel(
            name='TelefonosFeria',
        ),
        migrations.DeleteModel(
            name='TelefonosVendedor',
        ),
        migrations.AddField(
            model_name='feria',
            name='telefonos',
            field=models.ManyToManyField(to='ferias.Telefono'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='telefonos',
            field=models.ManyToManyField(to='ferias.Telefono'),
        ),
    ]
