# Generated by Django 3.2.7 on 2021-10-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferias', '0003_auto_20211018_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendedor',
            options={'verbose_name_plural': 'Vendedores'},
        ),
        migrations.AddField(
            model_name='feria',
            name='productos',
            field=models.ManyToManyField(blank=True, null=True, to='ferias.Producto'),
        ),
        migrations.AlterField(
            model_name='feria',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_ferias'),
        ),
        migrations.AlterField(
            model_name='feria',
            name='telefonos',
            field=models.ManyToManyField(blank=True, null=True, to='ferias.Telefono'),
        ),
        migrations.AlterField(
            model_name='feria',
            name='vendedores',
            field=models.ManyToManyField(blank=True, null=True, to='ferias.Vendedor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagenRepresentativa',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_vendedores'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='perfilFace',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='perfilInsta',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='sitioWeb',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
